FROM dockerfile/java:oracle-java8
MAINTAINER cherb <friendly12181@gmail.com>

ADD springboot_hdh-0.0.1-SNAPSHOT.jar /opt/springboot_hdh-0.0.1-SNAPSHOT/

WORKDIR /opt/springboot_hdh-0.0.1-SNAPSHOT/
CMD ["java", "springboot_hdh-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080








FROM dockerfile/java:oracle-java8
MAINTAINER cherb <friendly12181@gmail.com>

ADD hdh-0.0.1-SNAPSHOT.jar /opt/hdh-0.0.1-SNAPSHOT/

WORKDIR /opt/hdh-0.0.1-SNAPSHOT/
CMD java -jar hdh-0.0.1-SNAPSHOT.jar

EXPOSE 8080


